trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: 'coverage/target/site/jacoco-aggregate/jacoco.xml'
    reportDirectory: 'coverage/target/site/jacoco-aggregate'
    failIfCoverageEmpty: true

- bash: 'mvn coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN -DjacocoReports=./coverage/target/site/jacoco-aggregate/jacoco.xml'
  displayName: 'Upload Coverage to Coveralls'
  env:
    CI: true
    CI_NAME: azure-pipelines
    CI_BUILD_NUMBER: $(Build.BuildNumber)
    CI_BUILD_URL: $(Build.BuildUri)
    CI_BRANCH: $(Build.SourceBranchName)
    COVERALLS_REPO_TOKEN: $(CoverallsRepoToken)
