version: 2
jobs:
  build:
    working_directory: ~/cryptid-java

    docker:
      - image: circleci/openjdk:8-jdk-node

    steps:
      - checkout

      - restore_cache:
          key: cryptid-java-{{ checksum "pom.xml" }}
      
      - run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
      
      - save_cache:
          paths:
            - ~/.m2
          key: cryptid-java-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
